# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170818_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, choices=[('deposit', 'deposit'), ('WITHDRAWAL', 'withdrawal'), ('transfer', 'TRANSFER')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='api.Account'),
        ),
    ]
